bot_name: "Jon Snow the watcher"
icon_emoji: ":sleuth_or_spy:"
review_count: 20
google_play_location: "en"
app_store_location: "us"

# web_hook_uri: "Your slack incoming hook"
# google_play_app_id: "com.google.android.gm"
# app_store_app_id: "284882215"
